# Generated by Django 3.0.4 on 2020-05-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200430_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_list_allborrowed', 'List all borrowed book'))},
        ),
    ]
